DROP DATABASE IF EXISTS CMS_db;
CREATE DATABASE CMS_db;

\c CMS_db;

CREATE TABLE department (
  id SERIAL PRIMARY KEY,
  name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role (
  id SERIAL PRIMARY KEY,
  title VARCHAR(30) UNIQUE NOT NULL,
  salary DECIMAL NOT NULL,
  FOREIGN KEY (department_id) INTEGER NOT NULL REFERENCES department(id)
  ON DELETE SET NULL
);

CREATE TABLE employee (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  FOREIGN KEY (role_id) INTEGER NOT NULL REFERENCES role(id),
  FOREIGN KEY (manager_id) INTEGER DEFAULT NULL REFERENCES employee(id)
  ON DELETE SET NULL
);